### PR TITLE
Add sliced display mode

### PR DESCRIPTION
**Pull request by zogi**
Add a new display mode which renders transparent slices of the volume to
approximate Arnold 5 standard volume shader using single-scattering
equations.
The display mode uses a separate set of node attributes mimicking the
ones of the standard volume shader.

The slicing is done in an axis-aligned fashion by sampling the VDB grids
on a dense lattice. The volumes are cached up to a user-specified memory
limit to allow smooth animation of volumes.

The pull request also addresses Windows build issues and adds MtoA
support for the standard volume attributes used by the sliced display mode.
The MtoA extension translates vdb_visualizer Maya nodes to a volume node
and a standard_volume shader if compiled against Arnold 5.

These videos demonstate a few features of the sliced display mode:
https://drive.google.com/file/d/0Byp67-VQQtr2RE5CcHl0Z0E0Yms/view?usp=sharing (~52MB)
https://drive.google.com/file/d/0Byp67-VQQtr2YmlUWlJ6SVFZXzQ/view?usp=sharing (~2.4MB)

### CODE REVIEW

**Comment by sirpalee** [comment]
Hey! First of all, thanks for the pull request, the new features look exciting!

Secondly, I just pushed my work from yesterday and the last week or so, that has the initial pass at Arnold 5 compatibility and some code/feature cleanup for the plugin. Could you please update your PR, so we get rid of the conflicts?

One quick note about the dso parameter on the procedural. I don't think the extension matters at all, and we should be removing it (both the .so and .dll). When it comes to Arnold 4, it does append the right platform specific extension, and in case of Arnold 5, we don't need the dso anymore.

**Comment by zogi** [comment]
Hey! I've rebased my changes onto the tip of your master branch. Also removed the platform-specific procedural extension logic.

**Comment by sirpalee** [comment]
Thanks for doing that! I'll look through the changes and see how it works in our environment.

**Comment by sirpalee** [comment]
I tried to compile the changes, but there were two small issues.

When checking for the system name, you need to use STREQUAL, instead of EQUAL. And we have an older openvdb_render version that doesn't contain the class multiresgrid. I'm just going to merge in the changes, because otherwise the code looks good, and upgrade our internal build of openvdb. It was on my todo list for a while anyway.

**Comment by sirpalee** [comment]
A quick afterthought. I was sloppy when merging the changes. Please be careful next time when submitting a PR, new features should not disable old features completely. Worst case, make it clear in the initial comment what existing features or code paths are disabled.

**Comment by zogi** [comment]
Ok, I will be more careful next time. What old features are disabled by the PR?

**Comment by sirpalee** [comment]
Mostly MtoA translator related stuff. Some parameters mistranslated, I'm not sure if instanced volumes work fine, shader overrides did not export, the simple shader was disabled, the grid setup code was not running on connected shaders anymore and such. I'm still in the middle of reorganizing the translator code and testing all the features, so I might be wrong about some of these issues.

Something unrelated, did you test instanced volumes with the sliced display?

**Comment by zogi** [comment]
No, didn't test it with instanced volumes. To be honest, I would be very surprised if that worked, since the ogsfx effect wasn't written with hardware instancing in mind.

**Pull request merged**
